[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.3.3"
ic-cdk-macros = "0.3.3"
ic-types = "0.2.2"
serde = "1"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_with = "1.6.2"